"""
Python Course - Part 3

https://github.com/egalli64/pyco

Module 1 - Function

Parameters and arguments - mutable default parameter (don't do that)
"""

from random import randint


def roll_dice(values=[]):
    """Abusing a default parameter to cache values (confusing)"""
    values.append(randint(1, 6))
    print("Current values are:", values)


# first no-arg call generates an empty list - the other calls use it
for i in range(5):
    roll_dice()

# passing a value, the default value is not used
roll_dice([6, 6, 6])
# get back using the list generated by the first no-arg call
roll_dice()
